// Compact CEFR word lookup — covers the most commonly looked-up English words.
// Source: based on Oxford 5000 / CEFR canonical word lists.
// Words not in this map: AI path returns cefr from Claude; dictionary path shows no badge.
const CEFR_MAP: Record<string, string> = {
  // A1
  able:'A1',address:'A1',age:'A1',animal:'A1',answer:'A1',area:'A1',baby:'A1',
  bag:'A1',ball:'A1',bank:'A1',bed:'A1',big:'A1',bird:'A1',book:'A1',boy:'A1',
  bread:'A1',brother:'A1',bus:'A1',buy:'A1',car:'A1',cat:'A1',chair:'A1',
  child:'A1',children:'A1',city:'A1',class:'A1',cold:'A1',colour:'A1',
  come:'A1',computer:'A1',country:'A1',day:'A1',dinner:'A1',dog:'A1',door:'A1',
  drink:'A1',eat:'A1',end:'A1',evening:'A1',eye:'A1',face:'A1',family:'A1',
  father:'A1',find:'A1',food:'A1',foot:'A1',friend:'A1',girl:'A1',give:'A1',
  good:'A1',group:'A1',hand:'A1',happy:'A1',have:'A1',head:'A1',help:'A1',
  home:'A1',hospital:'A1',hotel:'A1',house:'A1',job:'A1',know:'A1',language:'A1',
  large:'A1',leave:'A1',letter:'A1',like:'A1',listen:'A1',little:'A1',live:'A1',
  look:'A1',love:'A1',lunch:'A1',man:'A1',men:'A1',minute:'A1',money:'A1',
  month:'A1',morning:'A1',mother:'A1',music:'A1',name:'A1',need:'A1',
  new:'A1',night:'A1',number:'A1',office:'A1',old:'A1',open:'A1',
  park:'A1',people:'A1',phone:'A1',photo:'A1',place:'A1',play:'A1',
  read:'A1',room:'A1',run:'A1',school:'A1',see:'A1',shop:'A1',sister:'A1',
  small:'A1',sport:'A1',start:'A1',stop:'A1',street:'A1',student:'A1',
  table:'A1',talk:'A1',teacher:'A1',telephone:'A1',television:'A1',think:'A1',
  time:'A1',today:'A1',town:'A1',train:'A1',tree:'A1',walk:'A1',want:'A1',
  water:'A1',week:'A1',woman:'A1',women:'A1',word:'A1',work:'A1',world:'A1',
  write:'A1',year:'A1',

  // A2
  accident:'A2',activity:'A2',actor:'A2',adult:'A2',afraid:'A2',agree:'A2',
  airport:'A2',alone:'A2',already:'A2',always:'A2',angry:'A2',another:'A2',
  appear:'A2',arrive:'A2',artist:'A2',ask:'A2',attempt:'A2',bad:'A2',
  beach:'A2',because:'A2',become:'A2',before:'A2',behind:'A2',believe:'A2',
  below:'A2',between:'A2',bicycle:'A2',break:'A2',bring:'A2',build:'A2',
  business:'A2',camp:'A2',catch:'A2',cause:'A2',change:'A2',cheap:'A2',
  check:'A2',choice:'A2',clean:'A2',clear:'A2',clever:'A2',close:'A2',
  clothes:'A2',college:'A2',common:'A2',compare:'A2',complete:'A2',
  continue:'A2',cook:'A2',correct:'A2',cost:'A2',cover:'A2',culture:'A2',
  dangerous:'A2',dark:'A2',decide:'A2',different:'A2',difficult:'A2',
  discover:'A2',distance:'A2',draw:'A2',dream:'A2',drive:'A2',drop:'A2',
  each:'A2',early:'A2',easy:'A2',enjoy:'A2',enough:'A2',enter:'A2',
  environment:'A2',especially:'A2',event:'A2',every:'A2',example:'A2',
  excellent:'A2',exciting:'A2',exercise:'A2',expect:'A2',experience:'A2',
  explain:'A2',fall:'A2',fast:'A2',feel:'A2',finally:'A2',follow:'A2',
  foreign:'A2',forget:'A2',free:'A2',fresh:'A2',garden:'A2',geography:'A2',
  get:'A2',half:'A2',high:'A2',history:'A2',holiday:'A2',honest:'A2',
  hope:'A2',hour:'A2',however:'A2',hungry:'A2',hurt:'A2',important:'A2',
  inside:'A2',interest:'A2',interesting:'A2',invite:'A2',join:'A2',
  journey:'A2',keep:'A2',kind:'A2',kitchen:'A2',learn:'A2',less:'A2',
  life:'A2',light:'A2',loud:'A2',lower:'A2',lucky:'A2',match:'A2',
  maybe:'A2',mean:'A2',meet:'A2',member:'A2',message:'A2',middle:'A2',
  modern:'A2',moment:'A2',natural:'A2',near:'A2',normal:'A2',offer:'A2',
  often:'A2',outside:'A2',page:'A2',paint:'A2',party:'A2',pay:'A2',
  picture:'A2',popular:'A2',prepare:'A2',problem:'A2',programme:'A2',
  project:'A2',proud:'A2',public:'A2',put:'A2',question:'A2',quiet:'A2',
  reason:'A2',remember:'A2',repeat:'A2',result:'A2',return:'A2',rich:'A2',
  right:'A2',river:'A2',road:'A2',safe:'A2',same:'A2',save:'A2',say:'A2',
  science:'A2',send:'A2',sentence:'A2',share:'A2',short:'A2',show:'A2',
  simple:'A2',since:'A2',situation:'A2',sleep:'A2',slow:'A2',
  smile:'A2',sometimes:'A2',special:'A2',spend:'A2',still:'A2',strong:'A2',
  suggest:'A2',sure:'A2',swim:'A2',take:'A2',team:'A2',test:'A2',
  themselves:'A2',together:'A2',told:'A2',top:'A2',travel:'A2',true:'A2',
  turn:'A2',understand:'A2',university:'A2',until:'A2',useful:'A2',
  usually:'A2',visit:'A2',voice:'A2',wait:'A2',warm:'A2',watch:'A2',
  weather:'A2',website:'A2',welcome:'A2',well:'A2',whole:'A2',wide:'A2',
  win:'A2',wish:'A2',wonder:'A2',wrong:'A2',young:'A2',

  // B1
  abandon:'B1',ability:'B1',absence:'B1',absolutely:'B1',
  accept:'B1',access:'B1',according:'B1',achieve:'B1',acknowledge:'B1',
  adapt:'B1',advanced:'B1',advantage:'B1',adventure:'B1',affect:'B1',
  afford:'B1',agent:'B1',aim:'B1',allow:'B1',although:'B1',ambition:'B1',
  amount:'B1',analysis:'B1',announce:'B1',anxiety:'B1',apply:'B1',
  approach:'B1',appropriate:'B1',approve:'B1',argument:'B1',arrange:'B1',
  article:'B1',aspect:'B1',assist:'B1',associate:'B1',atmosphere:'B1',
  attach:'B1',authority:'B1',available:'B1',avoid:'B1',aware:'B1',
  basic:'B1',benefit:'B1',border:'B1',challenge:'B1',characteristic:'B1',
  circumstance:'B1',citizen:'B1',claim:'B1',commit:'B1',communicate:'B1',
  community:'B1',concentrate:'B1',concept:'B1',concern:'B1',conclusion:'B1',
  condition:'B1',confident:'B1',confirm:'B1',connect:'B1',consider:'B1',
  consume:'B1',contain:'B1',contest:'B1',contract:'B1',contribute:'B1',
  conversation:'B1',creative:'B1',crime:'B1',crisis:'B1',criticism:'B1',
  current:'B1',deal:'B1',debate:'B1',decade:'B1',decrease:'B1',define:'B1',
  deliver:'B1',demand:'B1',design:'B1',despite:'B1',detail:'B1',
  determine:'B1',develop:'B1',difference:'B1',direct:'B1',discuss:'B1',
  distribution:'B1',economy:'B1',education:'B1',effect:'B1',efficient:'B1',
  effort:'B1',element:'B1',emergency:'B1',emotion:'B1',encourage:'B1',
  engage:'B1',establish:'B1',evidence:'B1',exist:'B1',
  expand:'B1',feature:'B1',focus:'B1',force:'B1',formal:'B1',function:'B1',
  general:'B1',generation:'B1',goal:'B1',government:'B1',growth:'B1',
  guide:'B1',handle:'B1',identify:'B1',imagine:'B1',impact:'B1',
  implement:'B1',improve:'B1',include:'B1',increase:'B1',independent:'B1',
  individual:'B1',industry:'B1',influence:'B1',inform:'B1',involve:'B1',
  issue:'B1',knowledge:'B1',lack:'B1',leader:'B1',likely:'B1',limit:'B1',
  local:'B1',major:'B1',manage:'B1',manner:'B1',method:'B1',model:'B1',
  movement:'B1',national:'B1',negative:'B1',network:'B1',notice:'B1',
  obtain:'B1',opportunity:'B1',option:'B1',overall:'B1',particular:'B1',
  performance:'B1',personal:'B1',physical:'B1',political:'B1',positive:'B1',
  potential:'B1',power:'B1',prefer:'B1',present:'B1',prevent:'B1',
  previous:'B1',primary:'B1',principle:'B1',process:'B1',produce:'B1',
  professional:'B1',progress:'B1',provide:'B1',purpose:'B1',quality:'B1',
  reality:'B1',receive:'B1',refer:'B1',reflect:'B1',relate:'B1',
  relationship:'B1',relative:'B1',relevant:'B1',rely:'B1',remove:'B1',
  replace:'B1',represent:'B1',require:'B1',research:'B1',resource:'B1',
  respond:'B1',responsibility:'B1',role:'B1',select:'B1',significant:'B1',
  society:'B1',solution:'B1',source:'B1',specific:'B1',statement:'B1',
  strategy:'B1',structure:'B1',support:'B1',technology:'B1',tend:'B1',
  theory:'B1',throughout:'B1',tradition:'B1',transfer:'B1',
  unique:'B1',value:'B1',variety:'B1',various:'B1',vehicle:'B1',version:'B1',
  via:'B1',view:'B1',whereas:'B1',

  // B2
  acute:'B2',advocate:'B2',albeit:'B2',allocate:'B2',ambiguous:'B2',
  ambitious:'B2',analogy:'B2',anticipate:'B2',arbitrary:'B2',assert:'B2',
  assumption:'B2',attribute:'B2',autonomous:'B2',bias:'B2',coherent:'B2',
  collaborate:'B2',commence:'B2',compelling:'B2',compensate:'B2',
  competent:'B2',complement:'B2',complex:'B2',complexity:'B2',
  comply:'B2',comprehensive:'B2',comprise:'B2',concede:'B2',conduct:'B2',
  consequence:'B2',considerable:'B2',constitute:'B2',constrain:'B2',
  contemplate:'B2',context:'B2',contradict:'B2',controversial:'B2',
  conventional:'B2',correspond:'B2',criterion:'B2',crucial:'B2',
  derive:'B2',dimension:'B2',diminish:'B2',discipline:'B2',discourse:'B2',
  distinct:'B2',distribute:'B2',diverse:'B2',domain:'B2',dominant:'B2',
  eliminate:'B2',emerge:'B2',emphasise:'B2',enforce:'B2',enormous:'B2',
  ensure:'B2',ethical:'B2',evaluate:'B2',evident:'B2',evolve:'B2',
  explicit:'B2',exploit:'B2',extent:'B2',facilitate:'B2',fundamental:'B2',
  generate:'B2',gradual:'B2',hierarchy:'B2',hypothesis:'B2',ideology:'B2',
  implicit:'B2',incorporate:'B2',indicate:'B2',inherent:'B2',initiative:'B2',
  insight:'B2',integrate:'B2',integrity:'B2',interact:'B2',interpret:'B2',
  intervene:'B2',investigate:'B2',justify:'B2',legislation:'B2',
  legitimate:'B2',manifest:'B2',mechanism:'B2',minimise:'B2',
  modify:'B2',monitor:'B2',motivation:'B2',mutual:'B2',narrative:'B2',
  objective:'B2',obligation:'B2',optimise:'B2',outcome:'B2',
  perspective:'B2',phenomenon:'B2',policy:'B2',precedent:'B2',
  predominant:'B2',predominantly:'B2',preliminary:'B2',principal:'B2',
  prioritise:'B2',proceed:'B2',promote:'B2',proportion:'B2',
  psychological:'B2',radical:'B2',rational:'B2',reinforce:'B2',
  restore:'B2',retain:'B2',reveal:'B2',scope:'B2',sector:'B2',
  seek:'B2',simulate:'B2',somewhat:'B2',subsequent:'B2',substantial:'B2',
  sufficient:'B2',supplement:'B2',sustainable:'B2',symbolic:'B2',
  thesis:'B2',transform:'B2',undermine:'B2',undertake:'B2',
  nonetheless:'B2',notwithstanding:'B2',paradigm:'B2',persist:'B2',

  // C1
  abstract:'C1',aesthetic:'C1',aggregate:'C1',alleviate:'C1',ambivalent:'C1',
  analogous:'C1',anomaly:'C1',articulate:'C1',aspiration:'C1',
  assimilate:'C1',astute:'C1',attrition:'C1',augment:'C1',
  bureaucracy:'C1',candid:'C1',capricious:'C1',catalyst:'C1',
  circumvent:'C1',clandestine:'C1',cogent:'C1',colloquial:'C1',
  complacent:'C1',connotation:'C1',contentious:'C1',convergence:'C1',
  covert:'C1',cynical:'C1',delineate:'C1',dichotomy:'C1',discern:'C1',
  disparate:'C1',eloquent:'C1',empirical:'C1',ephemeral:'C1',
  equivocal:'C1',exacerbate:'C1',exemplify:'C1',expedient:'C1',
  facade:'C1',fallacy:'C1',formidable:'C1',frugal:'C1',grandiose:'C1',
  hegemony:'C1',heuristic:'C1',hyperbole:'C1',idiosyncrasy:'C1',
  inadvertent:'C1',incoherent:'C1',incongruent:'C1',indiscriminate:'C1',
  inference:'C1',innate:'C1',insidious:'C1',intangible:'C1',intrinsic:'C1',
  juxtapose:'C1',laconic:'C1',lament:'C1',lucid:'C1',meticulous:'C1',
  nuance:'C1',obfuscate:'C1',obsolete:'C1',omnipresent:'C1',
  ostensibly:'C1',paradox:'C1',paramount:'C1',peripheral:'C1',
  pervasive:'C1',plausible:'C1',pragmatic:'C1',precipitate:'C1',
  preemptive:'C1',premise:'C1',profound:'C1',proliferate:'C1',
  propagate:'C1',reconcile:'C1',reductive:'C1',resilient:'C1',
  rhetoric:'C1',rigorous:'C1',scrutinise:'C1',sceptical:'C1',
  stagnant:'C1',subjective:'C1',succinct:'C1',superfluous:'C1',
  tangential:'C1',tenuous:'C1',ubiquitous:'C1',unambiguous:'C1',
  unprecedented:'C1',unravel:'C1',verbose:'C1',vindicate:'C1',volatile:'C1',
  wane:'C1',zealous:'C1',

  // C2
  abstruse:'C2',acrimony:'C2',anachronism:'C2',antithesis:'C2',
  apocryphal:'C2',arcane:'C2',bellicose:'C2',byzantine:'C2',
  chicanery:'C2',circumlocution:'C2',conundrum:'C2',diatribe:'C2',
  didactic:'C2',disingenuous:'C2',egregious:'C2',enervate:'C2',
  equanimity:'C2',erudite:'C2',esoteric:'C2',fatuous:'C2',
  grandiloquent:'C2',ignominious:'C2',impugn:'C2',incorrigible:'C2',
  inimitable:'C2',inscrutable:'C2',inveterate:'C2',loquacious:'C2',
  malfeasance:'C2',mendacious:'C2',obsequious:'C2',pernicious:'C2',
  perspicacious:'C2',polemic:'C2',prevaricate:'C2',pusillanimous:'C2',
  recalcitrant:'C2',sycophant:'C2',temerity:'C2',tendentious:'C2',
  truculent:'C2',turpitude:'C2',verisimilitude:'C2',vicissitude:'C2',
};

export function lookupCefr(word: string): string | undefined {
  return CEFR_MAP[word.toLowerCase().replace(/[^a-z]/g, '')];
}
